// filename: client/src/App.tsx | Code Generated by Sidekick is for learning and experimentation purposes only.

import type { ReactNode } from "react";

import { Link, NavLink, Navigate, Route, Routes } from "react-router-dom";

import "./App.css";

import AIAssistant from "./pages/AIAssistant";
import AuthPage from "./pages/AuthPage";
import Dashboard from "./pages/Dashboard";
import RecipeDetail from "./pages/RecipeDetail";
import Recipes from "./pages/Recipes";
import { getToken } from "./lib/auth";
import RecipeForm from "./pages/RecipeForm";


type PageProps = {
  title: string;
  description: string;
};

function PlaceholderPage({ title, description }: PageProps) {
  return (
    <section className="page-card">
      <p className="eyebrow">Spoonful</p>
      <h1>{title}</h1>
      <p>{description}</p>
    </section>
  );
}

function NavItem({ to, children }: { to: string; children: ReactNode }) {
  return (
    <NavLink
      className={({ isActive }) =>
        isActive ? "nav-link active" : "nav-link"
      }
      to={to}
    >
      {children}
    </NavLink>
  );
}

function ProtectedRoute({ children }: { children: ReactNode }) {
  return getToken() ? children : <Navigate to="/login" replace />;
}

function App() {
  return (
    <div className="app-shell">
      <header className="site-header">
        <Link className="brand" to="/recipes">
          Spoonful
        </Link>

        <nav className="site-nav" aria-label="Main navigation">
          <NavItem to="/recipes">Recipes</NavItem>
          <NavItem to="/dashboard">Dashboard</NavItem>
          <NavItem to="/ai-assistant">AI Assistant</NavItem>
          <NavItem to="/login">Log in</NavItem>
          <NavItem to="/signup">Sign up</NavItem>
        </nav>
      </header>

      <main className="site-main">
        <Routes>
          <Route path="/" element={<Navigate to="/recipes" replace />} />
          <Route path="/recipes" element={<Recipes />} />
          <Route
  path="/recipes/new"
  element={
    <ProtectedRoute>
      <RecipeForm />
    </ProtectedRoute>
  }
/>

<Route
  path="/recipes/:id/edit"
  element={
    <ProtectedRoute>
      <RecipeForm />
    </ProtectedRoute>
  }
/>
          <Route path="/recipes/:id" element={<RecipeDetail />} />
          <Route
            path="/dashboard"
            element={
              <ProtectedRoute>
                <Dashboard />
              </ProtectedRoute>
            }
          />
          <Route path="/login" element={<AuthPage mode="login" />} />
          <Route path="/signup" element={<AuthPage mode="signup" />} />
          <Route path="/ai-assistant" element={<AIAssistant />} />
          <Route
            path="*"
            element={
              <PlaceholderPage
                title="Page not found"
                description="The requested page does not exist."
              />
            }
          />
        </Routes>
      </main>
    </div>
  );
}

export default App;
